create table if not exists public.student_chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','active','expired','closed')),
  price_egp numeric(10,2) not null default 5 check (price_egp = 5),
  opened_at timestamptz,
  expires_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists student_chat_sessions_user_created_idx
on public.student_chat_sessions(user_id, created_at desc);

alter table public.student_chat_sessions enable row level security;

drop policy if exists "students read own chat sessions" on public.student_chat_sessions;
create policy "students read own chat sessions"
on public.student_chat_sessions for select
to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "students create own pending chat sessions" on public.student_chat_sessions;
create policy "students create own pending chat sessions"
on public.student_chat_sessions for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and status = 'pending'
  and opened_at is null
  and expires_at is null
);

drop policy if exists "admins update chat sessions" on public.student_chat_sessions;
create policy "admins update chat sessions"
on public.student_chat_sessions for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create table if not exists public.student_chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.student_chat_sessions(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_role text not null check (sender_role in ('student','admin')),
  message text not null check (length(trim(message)) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists student_chat_messages_session_created_idx
on public.student_chat_messages(session_id, created_at);

alter table public.student_chat_messages enable row level security;

drop policy if exists "participants read chat messages" on public.student_chat_messages;
create policy "participants read chat messages"
on public.student_chat_messages for select
to authenticated
using (
  exists (
    select 1
    from public.student_chat_sessions s
    where s.id = session_id
      and (s.user_id = (select auth.uid()) or (select private.is_admin()))
  )
);

drop policy if exists "students send active chat messages" on public.student_chat_messages;
create policy "students send active chat messages"
on public.student_chat_messages for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and sender_role = 'student'
  and exists (
    select 1
    from public.student_chat_sessions s
    where s.id = session_id
      and s.user_id = (select auth.uid())
      and s.status = 'active'
      and s.expires_at > now()
  )
);

drop policy if exists "admins send chat messages" on public.student_chat_messages;
create policy "admins send chat messages"
on public.student_chat_messages for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and sender_role = 'admin'
  and (select private.is_admin())
  and exists (
    select 1 from public.student_chat_sessions s
    where s.id = session_id
      and s.status = 'active'
      and s.expires_at > now()
  )
);

alter table public.manual_payment_requests
  add column if not exists chat_session_id uuid references public.student_chat_sessions(id) on delete cascade;

alter table public.manual_payment_requests
  drop constraint if exists manual_payment_target_check;

alter table public.manual_payment_requests
  add constraint manual_payment_target_check check (
    (target_type = 'lecture' and lecture_id is not null and module_code is null and chat_session_id is null and product_type in ('video','datashow','bundle'))
    or
    (target_type = 'module' and module_code is not null and lecture_id is null and chat_session_id is null and product_type in ('mcq','cases','osce'))
    or
    (target_type = 'chat' and lecture_id is null and module_code is null and chat_session_id is not null and product_type = 'chat')
  );

drop index if exists manual_payment_one_pending_per_product;
create unique index manual_payment_one_pending_per_product
on public.manual_payment_requests (
  user_id,
  target_type,
  coalesce(lecture_id, ''),
  coalesce(module_code, ''),
  coalesce(chat_session_id::text, ''),
  product_type
)
where status = 'pending';

create or replace function public.prepare_manual_payment_request()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_module public.module_products%rowtype;
  v_rule record;
  v_base integer;
begin
  if new.user_id is distinct from auth.uid() then
    raise exception 'Payment request must belong to the signed-in account';
  end if;

  select * into v_profile from public.profiles where id = auth.uid();
  if not found then raise exception 'Complete your student profile first'; end if;

  new.academic_year := v_profile.medical_year;
  new.transfer_reference := trim(new.transfer_reference);
  if new.transfer_reference = '' then raise exception 'Transaction reference is required'; end if;

  if not exists (
    select 1 from public.manual_payment_channels c
    where c.id = new.payment_method and c.active = true
  ) then raise exception 'This manual payment method is not active'; end if;

  if new.target_type = 'chat' then
    if not exists (
      select 1 from public.student_chat_sessions s
      where s.id = new.chat_session_id
        and s.user_id = auth.uid()
        and s.status = 'pending'
    ) then raise exception 'Chat session is not available for payment'; end if;
    new.amount_egp := 5;
    new.view_limit := null;

  elsif new.target_type = 'module' then
    select * into v_module
    from public.module_products
    where module_code = upper(trim(new.module_code))
      and product_type = new.product_type
      and enabled = true
      and academic_year = v_profile.medical_year
    limit 1;
    if not found then raise exception 'This module product is not available for your academic year'; end if;
    new.module_code := v_module.module_code;
    new.amount_egp := v_module.price_egp;
    new.view_limit := null;

  else
    select r.price_egp, r.view_limit into v_rule
    from public.lecture_pricing_rules r
    where r.lecture_id = new.lecture_id
      and r.product_type = new.product_type
      and r.enabled = true
      and (r.academic_year is null or r.academic_year = v_profile.medical_year)
      and (
        r.nationality_match = '*'
        or lower(r.nationality_match) = lower(coalesce(v_profile.nationality, ''))
        or (r.nationality_match = 'NON_EGYPTIAN' and lower(coalesce(v_profile.nationality, '')) not in ('egyptian','egypt'))
      )
    order by
      (case when r.academic_year is null then 0 else 20 end)
      + (case when r.nationality_match = '*' then 0 when r.nationality_match = 'NON_EGYPTIAN' then 5 else 10 end)
      + coalesce(r.priority, 0) desc
    limit 1;

    if found then
      new.amount_egp := v_rule.price_egp;
      new.view_limit := v_rule.view_limit;
    else
      select price_egp into v_base from public.lecture_settings
      where lecture_id = new.lecture_id and published = true and access_mode = 'paid';

      if found and coalesce(v_base,0) > 0 then
        if new.product_type = 'video' then new.amount_egp := v_base;
        elsif new.product_type = 'datashow' then new.amount_egp := greatest(30,v_base);
        else new.amount_egp := v_base + greatest(30,v_base);
        end if;
      elsif new.amount_egp <= 0 or new.amount_egp > 10000 then
        raise exception 'Invalid payment amount';
      end if;
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.review_manual_payment_request(
  p_request_id uuid,
  p_action text,
  p_note text default null
)
returns public.manual_payment_requests
language plpgsql
security invoker
set search_path = public
as $$
declare
  r public.manual_payment_requests%rowtype;
  e public.lecture_entitlements%rowtype;
  v_profile public.profiles%rowtype;
  v_video boolean;
  v_datashow boolean;
  v_adds_access boolean;
begin
  if not (select private.is_admin()) then raise exception 'Admin access required'; end if;
  if p_action not in ('approve','reject') then raise exception 'Invalid review action'; end if;

  select * into r from public.manual_payment_requests where id = p_request_id for update;
  if not found then raise exception 'Payment request not found'; end if;
  if r.status <> 'pending' then raise exception 'This payment request has already been reviewed'; end if;

  if p_action = 'reject' then
    update public.manual_payment_requests
    set status='rejected', admin_note=nullif(trim(p_note),''),
        reviewed_at=now(), reviewed_by=auth.uid()
    where id=r.id returning * into r;
    return r;
  end if;

  select * into v_profile from public.profiles where id = r.user_id;

  if r.target_type = 'chat' then
    update public.student_chat_sessions
    set status='active', opened_at=now(), expires_at=now()+interval '24 hours'
    where id=r.chat_session_id and user_id=r.user_id and status='pending';

    if not found then raise exception 'Chat session is no longer pending'; end if;

  elsif r.target_type = 'module' then
    insert into public.module_entitlements (
      user_id,module_code,product_type,academic_year,price_paid_egp,source,granted_at,expires_at,revoked_at
    ) values (
      r.user_id,r.module_code,r.product_type,r.academic_year,r.amount_egp,'manual:'||r.reference_code,now(),now()+interval '6 months',null
    )
    on conflict (user_id,module_code,product_type) do update
    set academic_year=excluded.academic_year, price_paid_egp=excluded.price_paid_egp,
        source=excluded.source, granted_at=now(), expires_at=now()+interval '6 months', revoked_at=null;

  else
    select * into e from public.lecture_entitlements where user_id=r.user_id and lecture_id=r.lecture_id;
    v_video := r.product_type in ('video','bundle');
    v_datashow := r.product_type in ('datashow','bundle');
    v_adds_access := (v_video and not coalesce(e.video_access,false)) or (v_datashow and not coalesce(e.datashow_access,false));
    if found and not v_adds_access and e.revoked_at is null then raise exception 'This lecture product is already active'; end if;

    insert into public.lecture_entitlements (
      user_id,lecture_id,price_paid_egp,source,granted_at,revoked_at,view_limit,views_used,
      offer_academic_year,offer_nationality,video_access,datashow_access,product_type
    ) values (
      r.user_id,r.lecture_id,r.amount_egp,'manual:'||r.reference_code,now(),null,
      case when v_video then r.view_limit else null end,0,r.academic_year,v_profile.nationality,
      v_video,v_datashow,
      case when v_video and v_datashow then 'bundle' when v_video then 'video' else 'datashow' end
    )
    on conflict (user_id,lecture_id) do update
    set price_paid_egp=public.lecture_entitlements.price_paid_egp+excluded.price_paid_egp,
        source=excluded.source,granted_at=now(),revoked_at=null,
        view_limit=case when excluded.video_access and not public.lecture_entitlements.video_access then excluded.view_limit else public.lecture_entitlements.view_limit end,
        views_used=case when excluded.video_access and not public.lecture_entitlements.video_access then 0 else public.lecture_entitlements.views_used end,
        offer_academic_year=excluded.offer_academic_year,offer_nationality=excluded.offer_nationality,
        video_access=public.lecture_entitlements.video_access or excluded.video_access,
        datashow_access=public.lecture_entitlements.datashow_access or excluded.datashow_access,
        product_type=case
          when (public.lecture_entitlements.video_access or excluded.video_access)
           and (public.lecture_entitlements.datashow_access or excluded.datashow_access) then 'bundle'
          when (public.lecture_entitlements.video_access or excluded.video_access) then 'video'
          else 'datashow'
        end;
  end if;

  update public.manual_payment_requests
  set status='approved',admin_note=nullif(trim(p_note),''),
      reviewed_at=now(),reviewed_by=auth.uid()
  where id=r.id returning * into r;

  return r;
end;
$$;

revoke all on function public.review_manual_payment_request(uuid,text,text) from public, anon;
grant execute on function public.review_manual_payment_request(uuid,text,text) to authenticated;
